#!/usr/bin/env python3
"""Render a boot splash draft into a Plymouth theme.

Each draft (N-name.html here) is an 800x480 page animated with plain CSS.
This steps its animations frame by frame in headless Chromium and writes a
Plymouth "script" theme named `carplay`, the name the Pi already boots with
and that ~/.xinitrc takes last_frame.png from:

  build/<draft>/carplay.plymouth, carplay.script
  build/<draft>/intro_NNN.png   played once
  build/<draft>/loop_NNN.png    repeated until X takes the screen
  build/<draft>/last_frame.png  full screen, first loop frame (X root bg)
  build/<draft>/frames.json     crop, colours and counts, for xsplash.py
  build/<draft>/preview.webp    intro once then the loop, for review

Frames are cropped to the area that ever changes; Plymouth fills the rest
with the page background. Needs python3-playwright with Chromium and PIL
(dev machine only; nothing here runs on the Pi).

  python3 render.py               render every draft
  python3 render.py 2-wheel       render one
  python3 render.py --serve       serve the drafts at http://localhost:8765/splash/
"""
import argparse
import http.server
import io
import json
import re
import threading
from pathlib import Path

from PIL import Image, ImageChops

HERE = Path(__file__).resolve().parent
WEB = HERE.parent / "web"
BUILD = HERE / "build"
FPS = 15          # frames advance every 2nd tick of Plymouth's 30 Hz refresh
W, H = 800, 480


class Handler(http.server.SimpleHTTPRequestHandler):
    """/splash/* from this directory, everything else from launcher/web, so
    the drafts can @import the launcher's stylesheet and fonts by URL."""

    def translate_path(self, path):
        path = path.split("?", 1)[0]
        if path.startswith("/splash/"):
            return str(HERE / path[len("/splash/"):])
        return str(WEB / path.lstrip("/"))

    def log_message(self, *args):
        pass


def serve(port):
    srv = http.server.ThreadingHTTPServer(("127.0.0.1", port), Handler)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    return srv


def capture(page, url):
    """Return (intro frames, loop frames, bg colour) for one draft."""
    page.goto(url)
    page.evaluate("document.fonts.ready")
    intro, loop = page.evaluate(
        "[+document.documentElement.dataset.intro, +document.documentElement.dataset.loop]")
    bg = page.evaluate("getComputedStyle(document.body).backgroundColor")
    page.evaluate("document.getAnimations().forEach(a => a.pause())")

    def shot(t):
        page.evaluate(f"document.getAnimations().forEach(a => a.currentTime = {t * 1000})")
        return Image.open(io.BytesIO(page.screenshot())).convert("RGB")

    n_intro, n_loop = round(intro * FPS), round(loop * FPS)
    frames_intro = [shot(i / FPS) for i in range(n_intro)]
    frames_loop = [shot(intro + i / FPS) for i in range(n_loop)]
    rgb = tuple(int(v) for v in re.findall(r"\d+", bg)[:3])
    return frames_intro, frames_loop, rgb


def changing_box(frames, bg):
    """Bounding box of everything that differs from the plain background."""
    plain = Image.new("RGB", (W, H), bg)
    box = None
    for f in frames:
        b = ImageChops.difference(f, plain).getbbox()
        if b:
            box = b if box is None else (min(box[0], b[0]), min(box[1], b[1]),
                                         max(box[2], b[2]), max(box[3], b[3]))
    return box or (0, 0, 1, 1)


SCRIPT = """\
# Generated by launcher/splash/render.py from {draft}.html. Edit the draft
# and re-render rather than editing this.
Plymouth.SetRefreshRate(30);
Window.SetBackgroundTopColor({r:.4f}, {g:.4f}, {b:.4f});
Window.SetBackgroundBottomColor({r:.4f}, {g:.4f}, {b:.4f});

n_intro = {n_intro};
n_loop = {n_loop};

fun pad3(n) {{
    d0 = Math.Int(n / 100); n = n - d0 * 100;
    d1 = Math.Int(n / 10);  d2 = n - d1 * 10;
    return "" + d0 + d1 + d2;
}}
for (i = 0; i < n_intro; i++) intro[i] = Image("intro_" + pad3(i) + ".png");
for (i = 0; i < n_loop; i++) loop[i] = Image("loop_" + pad3(i) + ".png");

# Frames were rendered for 800x480; centre them if the mode ever differs.
ox = (Window.GetWidth() - 800) / 2;
oy = (Window.GetHeight() - 480) / 2;

anim = Sprite();
anim.SetX(ox + {x});
anim.SetY(oy + {y});
if (n_intro > 0) anim.SetImage(intro[0]); else anim.SetImage(loop[0]);

# Firmware and kernel leave the panel black: fade up from that before the
# animation starts, rather than cutting to graphite.
veil = Sprite(Image("black.png").Scale(Window.GetWidth(), Window.GetHeight()));
veil.SetZ(100);
fade_ticks = 9;

tick = 0;
fun refresh_cb() {{
    tick++;
    if (tick <= fade_ticks) {{
        veil.SetOpacity(1 - tick / fade_ticks);
        return;
    }}
    f = Math.Int((tick - fade_ticks) / 2);
    if (f < n_intro) anim.SetImage(intro[f]);
    else anim.SetImage(loop[(f - n_intro) % n_loop]);
}}
Plymouth.SetRefreshFunction(refresh_cb);
"""

PLYMOUTH = """\
[Plymouth Theme]
Name=CarPlay
Description=CarPlay boot splash ({draft})
ModuleName=script

[script]
ImageDir=/usr/share/plymouth/themes/carplay
ScriptFile=/usr/share/plymouth/themes/carplay/carplay.script
"""


def write_theme(draft, intro, loop, bg):
    out = BUILD / draft
    out.mkdir(parents=True, exist_ok=True)
    for old in out.glob("*.png"):
        old.unlink()
    box = changing_box(intro + loop, bg)
    for i, f in enumerate(intro):
        f.crop(box).save(out / f"intro_{i:03}.png", optimize=True)
    for i, f in enumerate(loop):
        f.crop(box).save(out / f"loop_{i:03}.png", optimize=True)
    loop[0].save(out / "last_frame.png", optimize=True)
    Image.new("RGB", (1, 1), (0, 0, 0)).save(out / "black.png")
    r, g, b = (c / 255 for c in bg)
    (out / "carplay.script").write_text(SCRIPT.format(
        draft=draft, r=r, g=g, b=b, n_intro=len(intro), n_loop=len(loop),
        x=box[0], y=box[1]))
    (out / "carplay.plymouth").write_text(PLYMOUTH.format(draft=draft))
    (out / "frames.json").write_text(json.dumps({
        "draft": draft, "fps": FPS, "bg": list(bg), "x": box[0], "y": box[1],
        "n_intro": len(intro), "n_loop": len(loop)}) + "\n")

    seq = intro + loop * 3
    seq[0].save(out / "preview.webp", save_all=True, append_images=seq[1:],
                duration=round(1000 / FPS), loop=0, quality=90)
    size = sum(p.stat().st_size for p in out.glob("*_???.png"))
    print(f"{draft}: {len(intro)} intro + {len(loop)} loop frames, "
          f"crop {box}, {size // 1024} KiB of frames")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("drafts", nargs="*", help="draft names (default: all)")
    ap.add_argument("--serve", action="store_true", help="just serve the drafts for live preview")
    ap.add_argument("--port", type=int, default=8765)
    args = ap.parse_args()

    if args.serve:
        srv = http.server.ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
        print(f"http://localhost:{args.port}/splash/<draft>.html")
        srv.serve_forever()

    drafts = args.drafts or sorted(p.stem for p in HERE.glob("[0-9]-*.html"))
    from playwright.sync_api import sync_playwright
    srv = serve(0)
    port = srv.server_address[1]
    with sync_playwright() as pw:
        browser = pw.chromium.launch()
        page = browser.new_page(viewport={"width": W, "height": H})
        for d in drafts:
            write_theme(d, *capture(page, f"http://127.0.0.1:{port}/splash/{d}.html"))
        browser.close()
    srv.shutdown()


if __name__ == "__main__":
    main()
